apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shopfast.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: shopfast
  template:
    metadata:
      labels:
        app: shopfast
    spec:
      containers:
        - name: shopfast
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
