apiVersion: v1
kind: Service
metadata:
  name: {{ include "shopfast.name" . }}
  labels:
    {{- include "shopfast.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "LoadBalancer" }}
  ports:
    - name: http
      port: {{ .Values.service.port | default 80 }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "shopfast.selectorLabels" . | nindent 4 }}
    app: {{ include "shopfast.name" . }}
